### ISSUE TITLE
Load waveform but defer loading of audio file until Play is clicked

### ISSUE THREAD

**Issue by axis80** [michaeldzjap/waveplayer.js#10]
Is it possible to render the waveform from JSON file or data object, but defer loading of the actual MP3 audio file until you're actually ready to play the file?

My use case is that I have an infinite-scrolling page of players, each with a play button and waveform.  I obviously don't want to abuse my users' bandwidth by loading each and every audio file they scroll past.  I only want to actually load the MP3s that they play.  Buffer time is not a concern as my files are voice, not music.

I suppose I could render the waveforms into a div myself, then replace that with the player once play is clicked.  I worry that would cause flickering, or that I wouldn't be able to exactly replicate the look of your waveform.

**Comment by michaeldzjap** [comment]
> Is it possible to render the waveform from JSON file or data object, but defer loading of the actual MP3 audio file until you're actually ready to play the file?

No, this isn't possible currently, but it wouldn't be too much work to allow for this. Currently the `load()` function does both things, but I can implement two new additional function `loadWaveform()` and `loadAudio()` for separately handling the (initial) waveform drawing and loading the audio file.

Another option is to make the `preload` attribute of the HTML audio element configurable. Currently this is hardcoded to 'auto', but it would make more sense to allow the user to determine the value for this, and perhaps the default should even be 'metadata' instead of 'auto' come to think of it. However, it also says that:

> The browser is not forced by the specification to follow the value of this attribute; it is a mere hint.

That is kind of vague to say the least, but solely relying on the value of the `preload` attribute probably isn't sufficient.

So I will add both things in the next release. Not much time this week, but probably can do it somewhere next week.

**Comment by axis80** [comment]
loadWaveform() and loadAudio() sound like they would do the trick!

**Comment by michaeldzjap** [comment]
Just published [v1.2.0](https://github.com/michaeldzjap/waveplayer.js/tree/v1.2.0) which contains these new features.

**Comment by axis80** [comment]
That's awesome!  I'll test it out in the next few days.  Thanks!
