### ISSUE TITLE
Method for passing in JSON peaks on render

### ISSUE THREAD

**Issue by thespice** [michaeldzjap/waveplayer.js#8]
Again similar to wavesurfer, it would be a great idea to allow the option of passing in the json peak data onRender instead, keeping the current method of looking in the audio file dir for the .json file as the default fallback method.

In my use case the peak data is stored in a MongoDB collection so being able to define it onRender or load would be very helpful , eg : 

```
var wavePlayer = new WavePlayer({
    container: '#waveform',
    barWidth: 4,
    barGap: 1,
    height: 128
    options: {
       peaks: myPeakData
    }
});
```

Or even on a new load method : 

`wavePlayer.loadPeaks(myPeakData);`

**Comment by michaeldzjap** [comment]
Yes, this would make usage more flexible. Kind of restrictive to only allow waveform data to be loaded from .json. Will add this option in the next update.

**Comment by michaeldzjap** [comment]
Thinking about this a bit more now and I have come to the conclusion that probably it would be best to only allow passing of waveform data through a method (i.e. _not_ by passing it as a constructor argument). Reason being is that I want to keep the arguments you pass in via the constructor as generic as possible with regards to the playlist behaviour. In other words, it wouldn't make much sense to tie specific waveform data to a `WavePlayer` instance if you have a playlist with several different tracks. For instance, what should happen if you transition to the next track in the playlist? Should the waveform data you passed in as a constructor argument be invalidated? Makes things rather complicated.

In fact, I think it would be cleanest to allow for a second optional `data` parameter to the `load()` method. If this exists, it will be used as the source for drawing the waveform, otherwise it falls back to using the JSON file. This will also make it more easily extendible to the playlist case, as then you could pass an array of objects/arrays (in case of an URL and self supplied waveform data) or just an array of URL's (as is the case now) to `createPlaylist()`.

**Comment by michaeldzjap** [comment]
This feature has been added in [v1.1.0](https://github.com/michaeldzjap/waveplayer.js/tree/v1.1.0). Hope it works for you.
