### ISSUE TITLE
Disable scrubbing for radio streams

### ISSUE THREAD

**Issue by thespice** [michaeldzjap/waveplayer.js#9]
WavePlayer works just as great with live radio mp3 streams, simply by providing the url to the stream.

It would be great if there was someway of disabling the scrubbing for these situations as it's not really relevant. Would also be great to be able to disable the waveform display for live streams too. Even better would be the ability to specify a separate canvas element or even a jpg / png file to replace the waveform.

I know this could be done on a track by track basis by simply hiding the waveform container div, but if there was a way to specify all of this on load it would be awesome!

I know it's a big ask, but this is such a slick and compact bit of software that is just going to get better and better so I thought I'd throw some gauntlets down early :)

Keep up the great work Michael, wavePlayer is superb!

**Comment by thespice** [comment]
What would be truly sick is if, when playing a live stream as opposed to a regular mp3 file, it would automatically switch the waveform display out for an animated spectrum analyzer instead. It could use the exact same settings (bar width, space, colour etc) as you define when you init the player. But instead of rendering the peaks it would hook in the webaudio api and render an animated spectrum display. :)

**Comment by michaeldzjap** [comment]
I have to think about this one for a bit. Since the waveform for a live radio stream is not completely known (you only know its history) it isn't even possible to render the true waveform of the live stream. You could of course render a faux waveform, but yeah, skipping the playback head then no longer makes sense.

It wouldn't be too hard to allow for loading a custom image instead, but I think this is going beyond what I initially envisioned _waveplayer_ to be: a web based audio player with a waveform display. If you take the waveform display out of it, it is just an ordinary audio player essentially and I am sure there are quite a few of those around.

Regarding the spectrum analyzer idea. Yes, this would be cool, but again it goes beyond what I envisioned _waveplayer_ to be in essence. Also, I'd have to think how this could be integrated cleanly within the current code base. A sort of API plugin system like _wavesurfer_ offers would make this more easy, but this doesn't exist within _waveplayer_ (although I have thought about implementing it in the past, as I really liked the idea). But this is a lot of work for a small library with a small following like this. I just don't have time for it at the moment unfortunately.

**Comment by thespice** [comment]
Thanks Michael, totally understand what you are saying with regards to time constraints and it being a project with a small user base. With that in mind would you consider some freelance work on a project that I'm developing? If so, please let me know how we can get in touch to discuss it further.
